DROP TABLE USERS;
DROP TABLE ROLES;
DROP TABLE IOT_DEVICES;
DROP TABLE IOT_LOCATIONS;
DROP TABLE IOT_METRICS;

CREATE TABLE ROLES (
  ID_ROLE INT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_ROLE),
  CONSTRAINT ID_ROLE_UNIQUE UNIQUE  (ID_ROLE),
  CONSTRAINT NAME_UNIQUE UNIQUE  (NAME)
) ;

CREATE TABLE USERS (
  ID_USER INT NOT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  ID_ROLE INT NOT NULL DEFAULT 1,
  PASSWORD VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_USER),
  CONSTRAINT ID_USER_UNIQUE UNIQUE (ID_USER),
  CONSTRAINT EMAIL_UNIQUE UNIQUE (EMAIL),
  CONSTRAINT FK_USER_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLES (ID_ROLE) ON DELETE NO ACTION ON UPDATE NO ACTION
) ;

CREATE INDEX FK_USER_ROLE_IDX ON USERS (ID_ROLE);

CREATE TABLE IOT_DEVICES (
	ID_DEVICE INT NOT NULL,
	NAME VARCHAR(50) NULL,
	REFERENCE VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID_DEVICE)
);

CREATE TABLE IOT_LOCATIONS (
	ID_LOCATION INT NOT NULL,
	LONGITUDE DECIMAL(16,3) NOT NULL,
	LATITUDE DECIMAL(16,3) NOT NULL,
	PRIMARY KEY(ID_LOCATION)
);

CREATE TABLE IOT_METRICS (
	ID_METRIC INT NOT NULL,
	TEMPERATURE DECIMAL(16,3),
	HUMIDITY DECIMAL(16,3),
	WIND_SPEED DECIMAL(16,3),
	ID_USER INT NOT NULL,
	TIME TIMESTAMP NOT NULL,
	ID_DEVICE INT NOT NULL,
	LONGITUDE DECIMAL(16,3) NOT NULL,
	LATITUDE DECIMAL(16,3) NOT NULL,
	PRIMARY KEY(ID_METRIC)
);

CREATE UNIQUE INDEX FK_METRIC_USER_IDX ON IOT_METRICS (ID_USER);
CREATE UNIQUE INDEX FK_METRIC_DEVICE_IDX ON IOT_METRICS (ID_DEVICE);
CREATE UNIQUE INDEX FK_METRIC_LOCATION_IDX ON IOT_METRICS (ID_LOCATION);