DROP TABLE USERS;
DROP TABLE ROLES;
DROP TABLE TWEETS;
DROP TABLE TWITTER_USERS;

CREATE TABLE ROLES (
  ID_ROLE INT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_ROLE),
  CONSTRAINT ID_ROLE_UNIQUE UNIQUE  (ID_ROLE),
  CONSTRAINT NAME_UNIQUE UNIQUE  (NAME)
) ;

CREATE TABLE USERS (
  ID_USER INT NOT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  ID_ROLE INT NOT NULL DEFAULT 1,
  PASSWORD VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_USER),
  CONSTRAINT ID_USER_UNIQUE UNIQUE (ID_USER),
  CONSTRAINT EMAIL_UNIQUE UNIQUE (EMAIL),
  CONSTRAINT FK_USER_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLES (ID_ROLE) ON DELETE NO ACTION ON UPDATE NO ACTION
) ;

CREATE INDEX FK_USER_ROLE_IDX ON USERS (ID_ROLE);

CREATE TABLE TWITTER_USERS (
  --ID_TWITTER_USER INT NOT NULL,--NUESTRO ID
  EXTERNAL_ID BIGINT NOT NULL,
  SCREEN_NAME VARCHAR(255) DEFAULT NULL,
  NAME VARCHAR(255) DEFAULT NULL,
  URL VARCHAR(255) DEFAULT NULL,
  PROFILE_IMAGE_URL VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) DEFAULT NULL,
  LOCATION VARCHAR(255) DEFAULT NULL,
  CREATE_DATE BIGINT NOT NULL,
  LANGUAGE VARCHAR(255) NOT NULL,
  STATUSES_COUNT INT NOT NULL DEFAULT 0,
  FRIENDS_COUNT INT NOT NULL DEFAULT 0,
  FLLOWERS_COUNT INT NOT NULL DEFAULT 0,
  FAVORITES_COUNT INT NOT NULL DEFAULT 0,
  LISTED_COUNT INT NOT NULL DEFAULT 0,
  FOLLOWING BOOLEAN NOT NULL DEFAULT FALSE,
  FOLLOW_REQUEST_SENT BOOLEAN NOT NULL DEFAULT FALSE,
  NOTIFICATIONS_ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
  VERIFIED BOOLEAN NOT NULL DEFAULT FALSE,
  GEO_ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
  CONTRIBUTORS_ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
  TRASNALTOR BOOLEAN NOT NULL DEFAULT FALSE,
  TIME_ZONE VARCHAR(255) DEFAULT NULL,
  UTC_OFF_SET INT NOT NULL DEFAULT 0,
  SIDEBAR_BORDER_COLOR VARCHAR(255) DEFAULT NULL,
  SIDEBAR_FILL_COLOR VARCHAR(255) DEFAULT NULL,
  BACKGROUND_COLOR VARCHAR(255) DEFAULT NULL,
  BACKGROUND_IMAGE_URL VARCHAR(255) DEFAULT NULL,
  BACKGROUND_IMAGE_TILED BOOLEAN NOT NULL DEFAULT FALSE,
  TEXT_COLOR VARCHAR(255) DEFAULT NULL,
  LINK_COLOR VARCHAR(255) DEFAULT NULL,
  PROFILE_BANNER_URL VARCHAR(255) DEFAULT NULL,
  PROTECTD BOOLEAN DEFAULT FALSE,
  PROFILE_URL VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (EXTERNAL_ID)
) ;

CREATE TABLE TWEETS (
  --ID_TWEET INT NOT NULL,--NUESTRO ID
  TEXT VARCHAR(255) DEFAULT NULL,
  EXTERNAL_ID BIGINT NOT NULL,
  SOURCE VARCHAR(255) DEFAULT NULL,
  UNMODIFIED_TEXT VARCHAR(4000) DEFAULT NULL,
  FAVORITED BOOLEAN NOT NULL DEFAULT FALSE,
  RETWEETED BOOLEAN NOT NULL DEFAULT FALSE,
  FROM_USER_ID BIGINT NOT NULL DEFAULT '0',
  RETWEET_COUNT INT NOT NULL DEFAULT 0,
  LANGUAGE_CODE VARCHAR(255) NOT NULL,
  FAVORITE_COUNT INT NOT NULL DEFAULT 0,
  RETWEET BOOLEAN NOT NULL DEFAULT FALSE,
  FROM_USER VARCHAR(255) NOT NULL,
  CREATE_AT BIGINT NOT NULL,
  TO_USER_ID BIGINT NOT NULL DEFAULT '0',
  IN_REPLY_TO_SCREEN_NAME VARCHAR(255) DEFAULT NULL,
  IN_REPLY_TO_STATUS_ID BIGINT DEFAULT NULL,
  PROFILE_IMAGE_URL VARCHAR(255) NOT NULL,
  RETWEETED_STATUS VARCHAR(255) DEFAULT NULL,
  IN_REPLY_TO_USER_ID BIGINT DEFAULT NULL,
  --RETWEETED_COUNT INT NOT NULL DEFAULT 0,
  TWITTER_USER_ID BIGINT NOT NULL,
  PRIMARY KEY (EXTERNAL_ID),
  CONSTRAINT FK_TWEET_TWITTER_USER FOREIGN KEY (TWITTER_USER_ID) REFERENCES TWITTER_USERS (EXTERNAL_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ;

CREATE INDEX FK_TWEET_TWITTER_USER_IDX ON TWEETS (TWITTER_USER_ID);

