package com.controller;

import com.model.*;
import com.repository.*;
import com.model.Role;
import com.repository.Roles;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;

import java.util.Optional;

@RestController
@RequestMapping(path = "/role")
public class CtrlRole {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private Roles roleRepository;

    @GetMapping(path="/lst")
    public @ResponseBody Iterable<Role> listRoles() {
        // This returns a JSON or XML with the users
        return roleRepository.findAll();
    }

    @RequestMapping(path="/{id}", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Role> getRole(@PathVariable("id") long id){
        System.out.println("Fetching Role with id " + id);
        Optional<Role> r = roleRepository.findById(id);
        if (r.get() == null) {
            System.out.println("Role with id " + id + " not found");
            return new ResponseEntity<Role>(HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<Role>(r.get(), HttpStatus.OK);
    }
}
